### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by morphix9** [simonrauch/homebridge-optoma-projector-telnet#1]
Hey there,

I was waiting for a plugin like this for a while. Thanks!

But I have a problem to get it running:

```
Error: connect EHOSTUNREACH 10.0.2.111:23
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
```

My config:

```
"accessories": [
    {
        "accessory": "OptomaProjectorTelnet",
        "name": "Projector",
        "address": "10.0.2.111"
    }
]
```

@simonrauch Any idea what could be wrong?

**Comment by simonrauch** [comment]
Hey @morphix9 

this is my first homebridge plugin and i've thrown this thing together in an evening, so there are quite some issues.

If the telnet service of your projector is not reachable, Homebridge breaks. I'll try to push a fix for this soon. 

But what you could try to do, is figure out why your projector is not reachable. For my projector (UHD3000A) i had to do do a few things:

- Set `Power Mode(Standby)` to `Full Power Active`
- Set `Projector ID` to `1`: ID `0` did not work for me. (Also I'll make the projector ID configurable in the future.)
- Check `Projector Control Settings` if `Telnet` is activated and Network interface is configured correctly.

You can verify these settings manually by pinging the projector and opening a telnet connection from your computer. If the Projector still is not reachable, maybe try fully power cycling the projector. For me, sometimes the network interface of my projector seems to just die, if it was running for a long time. 🤷‍♂️

Hope this helps and i'll let you know, when i published the exception handling 👍

**Comment by simonrauch** [comment]
Hey @morphix9 

I've published a new version and added some exception handling. These errors shouldn't break Homebridge anymore. 

But the plugin still won't function correctly as long as the projector is not reachable. I'll close this issue, but feel free to contact me, if you still have trouble setting it up.

Cheers!

**Comment by morphix9** [comment]
Hey Simon,

thanks for your response. 

- My model is UHD51
- Telnet has been activated on the projector (was disabled by default)
- I set Power mode(Standby) to "Full power active" so it's reachable now even if turned off.
- I updated to your latest version, but the switch is not triggering anything

There is no error in the HB log:

```
[4/27/2020, 19:43:22] [Projector] Sending boot command
[4/27/2020, 19:43:26] [Projector] Sending shutdown command
[4/27/2020, 19:43:53] [Projector] Sending boot command
[4/27/2020, 19:44:08] [Projector] Sending shutdown command
```

Do you have any idea how to debug for my model? Can I try manually telnet a command?

Thanks for your help!

**Comment by morphix9** [comment]
How could I figure out the "projectorId"? I tried with `0`, but no change.
Btw, is the value for "projectorId" a string `"0"` or a integer `0`?

**Comment by simonrauch** [comment]
@morphix9 Yeah, that could be the issue. It shouldn't matter if it's a string or an integer, but it cannot be `0`. I think `0` means 'all projectors', and doesn't quite work. If the config is not defined the plugin defaults to the id `1`

Yeah sure, if you're able to open telnet on your projector you can try running the rs232 commands.

The plugin currently is only using these three:

- `~01150 1` get status
- `~0100 1` power on
- `~0100 2` power off

The first two digits are the projector ID, so if you have your projector set to ID 1, these commands should work. 

Here is the full list of commands, if you want to play around: https://www.optoma.de/uploads/RS232/DS309-RS232-en.pdf

**Comment by simonrauch** [comment]
@morphix9 For my model the setting for the projector ID is at `Projector Settings` > `Others` > `Projector ID`.

**Comment by morphix9** [comment]
Hey, got it running! I had to set the projector ID in the setup menu from 0 to 1. Now the ON/OFF is working.

Bu the status is not working - the switch says Off, but it's actually On. Unless I change the state via Homebridge. If I turn on/off via remote, the status is not changing. The same is when rebooting homebridge - the status is always set to off.

Do you check the status on plugin start up or how is it handled (how often do you check status)?

**Comment by simonrauch** [comment]
@morphix9 Currently i only have a few seconds timeout for checking the state. So the state is is checked whenever homebrige uses the getter (i'm not to sure, how often this happens).
If i have the 'Home' app open and i restart homebridge, the state doesn't get updated autmatically. If i  refresh the 'Home' app, it updates. For the IOS app you can force this getter by switching to a different app, and switching back. For the OSX app i usually quit out of the app and restart it.

**Comment by morphix9** [comment]
Hey, status still not working for me, even if I kill the Home app.

When I telnet I get this:

When it's turned on:

```
Optoma_PJ> ~01150 1
Pptoma_PJ> Ok101267170C0403
```

When it's turned off:

```
Optoma_PJ> ~01150
Optoma_PJ> F
```

Is this ok?
